# Generated by Django 6.0.3 on 2026-03-18 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Изделие'),
        ),
        migrations.AddField(
            model_name='production',
            name='worker',
            field=models.ForeignKey(limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
    ]
