# Generated by Django 6.0.3 on 2026-03-19 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Изделие'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='assigned_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person', verbose_name='Назначенный работник'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.production'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(through='core.PersonRole', to='core.role', verbose_name='Роли'),
        ),
        migrations.AlterUniqueTogether(
            name='personrole',
            unique_together={('person', 'role')},
        ),
    ]
