# Generated by Django 6.0.3 on 2026-03-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='specialization',
            field=models.CharField(choices=[('frame', 'Каркасник'), ('springs', 'Пружинщик / Механик'), ('sewing', 'Швея'), ('foam', 'Поролонщик'), ('upholstery', 'Обивщик'), ('none', 'Без специализации')], default='none', max_length=20, verbose_name='Специализация'),
        ),
    ]
