# Generated by Django 6.0.3 on 2026-03-18 16:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='date',
        ),
        migrations.RemoveField(
            model_name='production',
            name='worker',
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(choices=[('frame', 'Каркасник'), ('springs', 'Пружинщик / Механик'), ('sewing', 'Швея'), ('foam', 'Поролонщик'), ('upholstery', 'Обивщик'), ('none', 'Без специализации')], default='none', max_length=20, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='production',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн (только админ)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('worker', 'Работник')], default='worker', max_length=10),
        ),
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('started', 'В работе'), ('completed', 'Завершено')], default='started', max_length=10),
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('frame', 'Каркас'), ('springs', 'Пружины / Механизмы'), ('sewing', 'Шитьё'), ('foam', 'Поролон'), ('upholstery', 'Обивка')], max_length=20, verbose_name='Этап')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Завершено')], default='pending', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_worker', models.ForeignKey(limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Назначенный работник (админ может заменить)')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.production')),
            ],
            options={
                'verbose_name': 'Этап производства',
                'verbose_name_plural': 'Этапы производства',
                'ordering': ['production', 'stage_type'],
            },
        ),
    ]
