# Generated by Django 6.0.3 on 2026-03-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('started', 'В работе'), ('completed', 'Завершено')], default='started', max_length=10, verbose_name='Статус'),
        ),
    ]
