# Generated by Django 6.0.3 on 2026-03-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('core', '0004_production_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionstage',
            options={'ordering': ['production', 'order'], 'verbose_name': 'Этап производства', 'verbose_name_plural': 'Этапы производства'},
        ),
        migrations.RemoveField(
            model_name='production',
            name='person',
        ),
        migrations.AddField(
            model_name='production',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='production',
            name='current_stage_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущий этап (порядковый номер)'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок выполнения'),
        ),
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('started', 'В работе'), ('completed', 'Завершено')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
