# Generated by Django 6.0.3 on 2026-03-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_productionstage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('frame', 'Каркасник'), ('springs', 'Пружинщик / Механик'), ('sewing', 'Швея'), ('foam', 'Поролонщик'), ('upholstery', 'Обивщик')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='specialization',
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='core.specialization', verbose_name='Специализации'),
        ),
    ]
