# Generated by Django 6.0.3 on 2026-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_specialization_remove_person_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='specialization',
            field=models.CharField(choices=[('frame', 'Каркасник'), ('springs', 'Пружинщик / Механик'), ('sewing', 'Швея'), ('foam', 'Поролонщик'), ('upholstery', 'Обивщик')], default='none', max_length=20, verbose_name='Специализация'),
        ),
    ]
