# Generated by Django 6.0.3 on 2026-04-22 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_person_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('worker', 'Работник')], default='worker', max_length=10, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.person', verbose_name='Назначенный работник'),
        ),
    ]
