# Generated by Django 6.0.3 on 2026-04-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн этапа'),
        ),
    ]
