# Generated by Django 6.0.3 on 2026-04-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productionstage_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('uz', 'Oʻzbek')], default='ru', max_length=5),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Фото сотрудника'),
        ),
    ]
