# Generated by Django 6.0.3 on 2026-03-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('inventory', '0002_purchaserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractproduct',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В производстве'), ('completed', 'Выполнено')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contractproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='contractproduct',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
