# Generated by Django 6.0.3 on 2026-03-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Количество на складе')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Минимальный остаток')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за единицу')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название изделия')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена продажи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('in', 'Поступление'), ('out', 'Списание')], max_length=50, verbose_name='Тип')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material', verbose_name='Материал')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Транзакция материала',
                'verbose_name_plural': 'Транзакции материалов',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество на 1 изделие')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Материал изделия',
                'verbose_name_plural': 'Материалы изделий',
                'unique_together': {('product', 'material')},
            },
        ),
    ]
