# Generated by Django 6.0.3 on 2026-03-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaserequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('frame', 'Каркас'), ('springs', 'Пружины / Механизмы'), ('sewing', 'Шитьё'), ('foam', 'Поролон'), ('upholstery', 'Обивка')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Этап изделия',
                'verbose_name_plural': 'Этапы изделия',
                'ordering': ['order'],
                'unique_together': {('product', 'stage_type')},
            },
        ),
    ]
