# Generated by Django 6.0.3 on 2026-03-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='specialization',
            field=models.CharField(choices=[('frame', 'Каркасник'), ('springs', 'Пружинщик / Механик'), ('sewing', 'Швея'), ('foam', 'Поролонщик'), ('upholstery', 'Обивщик'), ('any', 'Общий (для всех)')], default='any', max_length=20, verbose_name='Для кого предназначен'),
        ),
        migrations.DeleteModel(
            name='ProductStage',
        ),
    ]
