# Generated by Django 6.0.3 on 2026-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_material_specialization_delete_productstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='min_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='material',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='material',
            name='specialization',
            field=models.CharField(choices=[('frame', 'Каркасник'), ('sewing', 'Швея'), ('foam', 'Поролонщик'), ('upholstery', 'Обивщик'), ('any', 'Общий (для всех)')], default='any', max_length=20, verbose_name='Для кого предназначен'),
        ),
    ]
