# Generated by Django 6.0.3 on 2026-04-22 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_material_min_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productmaterial',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ProductStageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('frame', 'Каркас'), ('springs', 'Пружины / Механизмы'), ('sewing', 'Шитьё'), ('foam', 'Поролон'), ('upholstery', 'Обивка')], max_length=20, verbose_name='Тип этапа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок выполнения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_templates', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Шаблон этапа изделия',
                'verbose_name_plural': 'Шаблоны этапов изделия',
                'ordering': ['order'],
                'unique_together': {('product', 'stage_type')},
            },
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='stage_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_materials', to='inventory.productstagetemplate', verbose_name='Шаблон этапа'),
        ),
    ]
