# Generated by Django 6.0.3 on 2026-04-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransaction',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за единицу'),
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Общая стоимость'),
        ),
    ]
