# Generated by Django 6.0.3 on 2026-03-18 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Себестоимость материалов')),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Прочие расходы')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена продажи')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Прибыль')),
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.production', verbose_name='Производство')),
            ],
            options={
                'verbose_name': 'Прибыль',
                'verbose_name_plural': 'Прибыль',
            },
        ),
    ]
