# Generated by Django 6.0.3 on 2026-03-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Выручка')),
                ('material_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Себестоимость материалов')),
                ('salary_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Затраты на зарплату')),
                ('profit_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Прибыль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Изделие')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.production', verbose_name='Производство')),
            ],
            options={
                'verbose_name': 'Прибыль',
                'verbose_name_plural': 'Прибыль',
            },
        ),
    ]
