# Generated by Django 6.0.3 on 2026-03-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='other_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Прочие расходы'),
        ),
        migrations.AddField(
            model_name='profit',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Прибыль (старое поле)'),
        ),
        migrations.AddField(
            model_name='profit',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Себестоимость материалов'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='production',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.production', verbose_name='Производство'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='profit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Прибыль'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выручка'),
        ),
    ]
