# Generated by Django 6.0.3 on 2026-04-24 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_role_and_more'),
        ('reports', '0002_profit_other_cost_profit_profit_profit_selling_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма начисления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.production', verbose_name='Производство')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Зарплата сотрудника',
                'verbose_name_plural': 'Зарплаты сотрудников',
            },
        ),
    ]
