# Generated by Django 6.0.3 on 2026-04-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_workersalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyOverhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True, verbose_name='Месяц (указывайте 1-е число)')),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Аренда')),
                ('utilities_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ЖКХ + Интернет')),
            ],
            options={
                'verbose_name': 'Общие расходы',
                'verbose_name_plural': 'Общие расходы',
                'ordering': ['-month'],
            },
        ),
    ]
